version: "3.9"

services:
  web:
    container_name: datatalk-web
    build: .
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - datatalk_services

networks:
  datatalk_services:
